// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaG4_0ieeSZR7P0t0_yq31qRCrIADqKDw',
    appId: '1:516980046851:web:98d5fc46cd53bfa1bd6236',
    messagingSenderId: '516980046851',
    projectId: 'e-commerce-demo-f7da6',
    authDomain: 'e-commerce-demo-f7da6.firebaseapp.com',
    storageBucket: 'e-commerce-demo-f7da6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PQt-7NQ5R0iMKHjnoAqP9nUzD9J--qo',
    appId: '1:516980046851:android:1c79e3fcf2b67c95bd6236',
    messagingSenderId: '516980046851',
    projectId: 'e-commerce-demo-f7da6',
    storageBucket: 'e-commerce-demo-f7da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ZrkoHnxyPF_ry9VKWAgsyOJ5b6FStLU',
    appId: '1:516980046851:ios:3812dcc8247b4010bd6236',
    messagingSenderId: '516980046851',
    projectId: 'e-commerce-demo-f7da6',
    storageBucket: 'e-commerce-demo-f7da6.appspot.com',
    iosBundleId: 'com.example.eCommerceDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ZrkoHnxyPF_ry9VKWAgsyOJ5b6FStLU',
    appId: '1:516980046851:ios:3812dcc8247b4010bd6236',
    messagingSenderId: '516980046851',
    projectId: 'e-commerce-demo-f7da6',
    storageBucket: 'e-commerce-demo-f7da6.appspot.com',
    iosBundleId: 'com.example.eCommerceDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaG4_0ieeSZR7P0t0_yq31qRCrIADqKDw',
    appId: '1:516980046851:web:1cf5997cb38367bdbd6236',
    messagingSenderId: '516980046851',
    projectId: 'e-commerce-demo-f7da6',
    authDomain: 'e-commerce-demo-f7da6.firebaseapp.com',
    storageBucket: 'e-commerce-demo-f7da6.appspot.com',
  );
}
